name: Deploy Production
on:
  push:
    branches:
      - main
      - actions

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: login to server and deploy
      run: |
        KEYFILE="./deploy_key"
        mkdir ~/.ssh
        touch $KEYFILE
        touch ~/.ssh/known_hosts
        echo "${{ secrets.PROD_SERVER_SSH_KEY }}" > $KEYFILE
        ssh-keyscan -H ${{ secrets.PROD_SERVER_HOST }} >> ~/.ssh/known_hosts
        ssh -i $KEYFILE ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_HOST }}
        echo $(ls -l)
        
        
