name: Deploy Production
on:
  push:
    branches:
      - main
      - actions

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: login to server and deploy
      run: |
        SSH_PATH="$HOME/.ssh"
        mkdir $SSH_PATH
        KEYFILE="$SSH_PATH/deploy_key"
        touch $KEYFILE
        touch "$SSH_PATH/known_hosts"
        chmod 600 $KEYFILE
        echo "${{ secrets.PROD_SERVER_SSH_KEY }}" > $KEYFILE
        ssh-keyscan -H ${{ secrets.PROD_SERVER_HOST }} >> "$SSH_PATH/known_hosts"
        ssh -i $KEYFILE ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_HOST }}
        echo $(ls -l)
        
        
