name: Deploy Production
on:
  push:
    branches:
      - main
      - actions

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: login to server and deploy
      run: |
        ssh -i ${{ secrets.PROD_SERVER_SSH_KEY }} ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_HOST }}
        echo $(ls -l)
        
        
